# 1. Specify the version for docker-compose.yml
version: "3.8"

# 2. Generate the serivces needed (redis)
services:
  web:
    build: .
    ports:
      - 3000:3000
    env_file: .env

  redis:
    container_name: "redis"
    image: redis:latest
    # Specify the redis.conf file to use and add a password.
    ports:
      - "6379:6379"
    # map the volumes to that redis has the custom conf file from this project.
